### ISSUE TITLE
How to change the icon of menutray?

### ISSUE THREAD

**Issue by pr0letariat** [trizen/menutray#5]
At the moment the icon looks like this:
![selection_001](https://cloud.githubusercontent.com/assets/14975253/13532276/81fe1998-e222-11e5-8dfa-4235451658dc.png)

How do I change it?

**Comment by trizen** [comment]
Menutray just introduced yesterday an option for changing the status icon by changing the configuration option `menutray_icon` (in `~/.config/menutray/config.pl`), which by default has the value `start-here`. (for more info, see the commit at: https://github.com/trizen/menutray/commit/2b90c5131f6ca6218b2553b9566a15d7d501dd7d)

Any icon name can be used instead, such as: `archlinux-logo`, `distributor-logo-gentoo`, etc...

**Comment by pr0letariat** [comment]
So in the `$CONFIG` block in `config.pl` add something like:

`"menutray_icon"          => "/home/me/Pictures/myicon.png"` ?

**Comment by trizen** [comment]
Yes, but currently, menutray does not support icon paths, only icon names, such as:

`menutray_icon => "myicon"`

...assumming that an icon named "myicon" exists in your current icons theme.

In order for this option to work, make sure your version of menutray is >= 0.45 (check `menutray -v`), otherwise update to the latest commit.
